# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches:
      - main  # Set a branch that will trigger a deployment
  schedule:
    - cron: '0 12 * * *' # Every day at noon
  
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write 
  pages: write
  id-token: write
  
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
      run: pip install -r requirements.txt
   
    - name: Create new content
      shell: bash
      env:
         API_KEY: ${{ secrets.API_KEY }}
      run: |
        python main.py

    - name: "Commit new content"
    - uses: EndBug/add-and-commit@v9
      with:
        add: '["content/posts/*.md", "static/images/*.jpg"]'

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build website
      run: hugo --minify
      
    - name: Upload website
      uses: actions/upload-pages-artifact@v1
      with:
        path: './public'
        
    - name: Publish at website
      id: deployment
      if: github.ref == 'refs/heads/main'
      uses: actions/deploy-pages@v1
    